# Generated by Django 5.1.5 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_flight_crew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="crew",
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                related_name="flights", to="airport.crew"
            ),
        ),
    ]
