# Generated by Django 5.1.5 on 2025-01-28 13:11

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_remove_flight_crew_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.image_upload
            ),
        ),
    ]
